version: "3.9"

services:
  knb:
    build: .
    command:
      - uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:16.4
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - .env
    expose:
      - 5432
    container_name: postgresql_db